version: "2"
services:
  gatsby:
    build: .
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "8001:8000"
      - "9229:9229" # For node profiling and debugging
    command: "npm run-script docker:start"