name: CI
on: push
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Scan for security issues
        run: npm audit
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache Gatsby cache folder
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cache-gatsby
          restore-keys: |
            ${{ runner.os }}-cache-gatsby
      - name: Cache Gatsby build folder
        uses: actions/cache@v2
        with:
          path: ~/public
          key: ${{ runner.os }}-public-gatsby
          restore-keys: |
            ${{ runner.os }}-public-gatsby
      - name: Install dependencies
        run: npm ci
#      - name: Build site
#        run: npm run build
      - name: Compress build
        run: zip -r public.zip ./public
      - name: Finished build stats
        run: |
          echo "Number of files in build folder:"
          find ./public -type f | wc -l
          echo "Size of build folder:"
          du -hd 0 ./public
          echo "Size of compressed build:"
          du -h ./public.zip
#      - name: Deploy to Netlify
#        uses: nwtgck/actions-netlify@v1.1
#        with:
#          publish-dir: './public.zip'
#          production-branch: master
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          deploy-message: "Deploy from GitHub Actions"
#        env:
#          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#        timeout-minutes: 3
      - name: Deploy to Netlify
        run: |
          curl -H "Content-Type: application/zip" \
            -H "Authorization: Bearer ${{ secrets.NETLIFY_AUTH_TOKEN }}"
            --data-binary "@public.zip" \
            https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}/deploys

